[package]
name = "mtl-monitor"
version = "0.40.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
async-trait = "0.1.51"
clap = "3.0.0-beta.4"
meio = "0.94.0"
rate-config = "0.40.0"
reqwest = "0.11.4"
rillrate = "0.40.0"
tokio = "1.11.0"

[build-dependencies]
rate-config = "0.40.0"
