[package]
name = "mtl-docker"
version = "0.40.0"
edition = "2018"

[dependencies]
anyhow = "1.0.44"
futures = "0.3.17"
log = "0.4.14"
rillrate = "0.40.0"
shiplift = { git = "https://github.com/softprops/shiplift" }
tokio = "1.11.0"
